---
name: Apache2-AuthenNTLM-Cookie
version: 0.01
author:
  - 'Laurent Dami <la_____.da__@etat.ge.ch>'
abstract: Store NTLM identity in a cookie
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Apache2::AuthenNTLM: 0
  Apache2::Cookie: 0
  Apache2::Directive: 0
  Apache2::RequestRec: 0
  Digest::SHA1: 0
build_requires:
  Test::More: 0
provides:
  Apache2::AuthenNTLM::Cookie:
    file: lib/Apache2/AuthenNTLM/Cookie.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
